# Generated by Django 4.2 on 2023-05-17 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Earthquake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.DecimalField(decimal_places=1, max_digits=5)),
                ("time", models.CharField(max_length=50)),
                ("longitude", models.DecimalField(decimal_places=2, max_digits=10)),
                ("latitude", models.DecimalField(decimal_places=2, max_digits=10)),
                ("depth", models.PositiveIntegerField()),
                ("location", models.CharField(max_length=100)),
                ("province", models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
