# Generated by Django 4.2 on 2023-05-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extremeweather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=50)),
                ("time", models.CharField(max_length=50)),
                ("province", models.CharField(max_length=10)),
            ],
        ),
    ]
