# Generated by Django 4.2 on 2023-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_extremeweather"),
    ]

    operations = [
        migrations.CreateModel(
            name="Device_items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=20)),
                ("device_id", models.CharField(blank=True, max_length=10, null=True)),
                ("MAC", models.CharField(max_length=20)),
                ("IP", models.CharField(max_length=20)),
                ("area", models.CharField(max_length=20)),
                ("netstatus", models.CharField(max_length=10)),
                ("authentication", models.CharField(max_length=10)),
                ("longitude", models.DecimalField(decimal_places=2, max_digits=5)),
                ("latitude", models.DecimalField(decimal_places=2, max_digits=5)),
                ("battery", models.CharField(max_length=10)),
            ],
        ),
    ]
