# Generated by Django 4.2 on 2023-05-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_device_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device_items",
            name="device_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
