# Generated by Django 4.1 on 2023-05-18 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_device_items_device_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("taskname", models.CharField(max_length=20)),
                ("tasktype", models.CharField(max_length=20)),
                ("longitude", models.DecimalField(decimal_places=2, max_digits=5)),
                ("latitude", models.DecimalField(decimal_places=2, max_digits=5)),
                ("radius", models.DecimalField(decimal_places=2, max_digits=10)),
                ("distribution", models.CharField(max_length=50)),
            ],
        ),
    ]
