# Generated by Django 4.1 on 2023-05-18 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="creationtime",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
