# Generated by Django 4.1 on 2023-06-26 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_task_creationtime"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="creationmonth",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
